<?php

declare(strict_types=1);

namespace SengentoBV\ChronopostSdk\Soap\ShippingService;

/**
 * Class which returns the class map definition
 * @package ChronoApi
 */
class ChronoShippingApiClassMap
{
    /**
     * Returns the mapping between the WSDL Structs and generated Structs' classes
     * This array is sent to the \SoapClient when calling the WS
     * @return string[]
     */
    final public static function get(): array
    {
        return [
            'shipperValue' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShipperValue',
            'resultFaisabiliteESD' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiResultFaisabiliteESD',
            'esdValue' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiEsdValue',
            'headerValue' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiHeaderValue',
            'customerValue' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiCustomerValue',
            'recipientValue' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiRecipientValue',
            'refValue' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiRefValue',
            'skybillValue' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiSkybillValue',
            'skybillParamsValue' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiSkybillParamsValue',
            'resultExpeditionValue' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiResultExpeditionValue',
            'resultGetReservedSkybillWithTypeValue' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiResultGetReservedSkybillWithTypeValue',
            'donneurDOrdre' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiDonneurDOrdre',
            'adresseEnlevement' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiAdresseEnlevement',
            'adresseEnlevementV2' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiAdresseEnlevementV2',
            'adresseEnlevementV3' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiAdresseEnlevementV3',
            'particularitesEsd' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiParticularitesEsd',
            'options' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiOptions',
            'resultEnlevementNational' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiResultEnlevementNational',
            'infoEnlevement' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiInfoEnlevement',
            'scheduledValue' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiScheduledValue',
            'appointmentValue' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiAppointmentValue',
            'esdWithRefClientValue' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiEsdWithRefClientValue',
            'esdWithRefClientValueV2' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiEsdWithRefClientValueV2',
            'resultReservationExpeditionValue' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiResultReservationExpeditionValue',
            'esdValue3' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiEsdValue3',
            'skybillWithDimensionsValue' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiSkybillWithDimensionsValue',
            'skybillWithDimensionsValueV2' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiSkybillWithDimensionsValueV2',
            'skybillWithDimensionsValueV3' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiSkybillWithDimensionsValueV3',
            'skybillParamsValueV2' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiSkybillParamsValueV2',
            'resultShippingValue' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiResultShippingValue',
            'resultMultiParcelExpeditionValue' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiResultMultiParcelExpeditionValue',
            'resultMultiParcelValue' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiResultMultiParcelValue',
            'skybillValueV2' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiSkybillValueV2',
            'resultReservationExpeditionValueV2' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiResultReservationExpeditionValueV2',
            'resultGetReservedSkybillValue' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiResultGetReservedSkybillValue',
            'resultReservationMultiParcelExpeditionValue' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiResultReservationMultiParcelExpeditionValue',
            'resultParcelValue' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiResultParcelValue',
            'shipperValueV2' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShipperValueV2',
            'recipientValueV2' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiRecipientValueV2',
            'refValueV2' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiRefValueV2',
            'skybillWithDimensionsValueV4' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiSkybillWithDimensionsValueV4',
            'skybillWithDimensionsValueV5' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiSkybillWithDimensionsValueV5',
            'skybillWithDimensionsValueV6' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiSkybillWithDimensionsValueV6',
            'recipientLocalValue' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiRecipientLocalValue',
            'recipientLocalValueV2' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiRecipientLocalValueV2',
            'customsValue' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiCustomsValue',
            'articleValue' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiArticleValue',
            'headerValueV2' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiHeaderValueV2',
            'resultReservationMultiParcelExpeditionValueV2' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiResultReservationMultiParcelExpeditionValueV2',
            'resultExpeditionValueV3' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiResultExpeditionValueV3',
            'resultMonoParcelExpeditionValue' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiResultMonoParcelExpeditionValue',
            'esdResultContraintesAgenceValue' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiEsdResultContraintesAgenceValue',
            'esdContraintesAgence' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiEsdContraintesAgence',
            'resultAnnulerEnlevement' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiResultAnnulerEnlevement',
            'statut' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiStatut',
            'entry' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiEntry',
            'destinatairesDpd' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiDestinatairesDpd',
            'destinataireDpd' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiDestinataireDpd',
            'adresseDestinataire' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiAdresseDestinataire',
            'infoClient' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiInfoClient',
            'particularites' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiParticularites',
            'particularitesColisDpd' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiParticularitesColisDpd',
            'infoDouanieres' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiInfoDouanieres',
            'resultPickupOrCollectionRequest' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiResultPickupOrCollectionRequest',
            'skybillValueBase' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiSkybillValueBase',
            'resultShippingInfo' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiResultShippingInfo',
            'error' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiError',
            'detail' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiDetail',
            'shippingInfo' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingInfo',
            'resultGetRouting' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiResultGetRouting',
            'geopostResult' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiGeopostResult',
            'faisabiliteESD' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiFaisabiliteESD',
            'faisabiliteESDResponse' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiFaisabiliteESDResponse',
            'shippingV2' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingV2',
            'shippingV2Response' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingV2Response',
            'getReservedSkybillWithTypeAndModeAuth' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiGetReservedSkybillWithTypeAndModeAuth',
            'getReservedSkybillWithTypeAndModeAuthResponse' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiGetReservedSkybillWithTypeAndModeAuthResponse',
            'getReservedSkybillWithType' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiGetReservedSkybillWithType',
            'getReservedSkybillWithTypeResponse' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiGetReservedSkybillWithTypeResponse',
            'creerEnlevementNational' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiCreerEnlevementNational',
            'creerEnlevementNationalResponse' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiCreerEnlevementNationalResponse',
            'shippingV3' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingV3',
            'shippingV3Response' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingV3Response',
            'getReservedSkybillWithTypeAndModeByReservation' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiGetReservedSkybillWithTypeAndModeByReservation',
            'getReservedSkybillWithTypeAndModeByReservationResponse' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiGetReservedSkybillWithTypeAndModeByReservationResponse',
            'shippingWithESDOnlyV2' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingWithESDOnlyV2',
            'shippingWithESDOnlyV2Response' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingWithESDOnlyV2Response',
            'shippingMultiParcel' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingMultiParcel',
            'shippingMultiParcelResponse' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingMultiParcelResponse',
            'shippingWithReservationV2' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingWithReservationV2',
            'shippingWithReservationV2Response' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingWithReservationV2Response',
            'shipping' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShipping',
            'shippingResponse' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingResponse',
            'getReservedSkybill' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiGetReservedSkybill',
            'getReservedSkybillResponse' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiGetReservedSkybillResponse',
            'shippingMultiParcelWithReservation' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingMultiParcelWithReservation',
            'shippingMultiParcelWithReservationResponse' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingMultiParcelWithReservationResponse',
            'shippingMultiParcelV4' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingMultiParcelV4',
            'shippingMultiParcelV4Response' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingMultiParcelV4Response',
            'shippingMultiParcelV5' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingMultiParcelV5',
            'shippingMultiParcelV5Response' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingMultiParcelV5Response',
            'shippingMultiParcelWithReservationV3' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingMultiParcelWithReservationV3',
            'shippingMultiParcelWithReservationV3Response' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingMultiParcelWithReservationV3Response',
            'shippingMultiParcelV2' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingMultiParcelV2',
            'shippingMultiParcelV2Response' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingMultiParcelV2Response',
            'shippingV6' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingV6',
            'shippingV6Response' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingV6Response',
            'shippingWithReservation' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingWithReservation',
            'shippingWithReservationResponse' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingWithReservationResponse',
            'shippingV7' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingV7',
            'shippingV7Response' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingV7Response',
            'rechercherContraintesEnlevement' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiRechercherContraintesEnlevement',
            'rechercherContraintesEnlevementResponse' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiRechercherContraintesEnlevementResponse',
            'annulerEnlevements' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiAnnulerEnlevements',
            'annulerEnlevementsResponse' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiAnnulerEnlevementsResponse',
            'creerEnlevementEurope' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiCreerEnlevementEurope',
            'creerEnlevementEuropeResponse' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiCreerEnlevementEuropeResponse',
            'shippingWithReservationAndESDWithRefClient' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingWithReservationAndESDWithRefClient',
            'shippingWithReservationAndESDWithRefClientResponse' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingWithReservationAndESDWithRefClientResponse',
            'getReservedSkybillWithTypeAndMode' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiGetReservedSkybillWithTypeAndMode',
            'getReservedSkybillWithTypeAndModeResponse' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiGetReservedSkybillWithTypeAndModeResponse',
            'shippingV4' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingV4',
            'shippingV4Response' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingV4Response',
            'shippingWithReservationAndESDWithRefClientPC' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingWithReservationAndESDWithRefClientPC',
            'shippingWithReservationAndESDWithRefClientPCResponse' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingWithReservationAndESDWithRefClientPCResponse',
            'shippingV5' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingV5',
            'shippingV5Response' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingV5Response',
            'shippingMultiParcelWithReservationV2' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingMultiParcelWithReservationV2',
            'shippingMultiParcelWithReservationV2Response' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingMultiParcelWithReservationV2Response',
            'shippingWithESDOnly' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingWithESDOnly',
            'shippingWithESDOnlyResponse' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingWithESDOnlyResponse',
            'getShippingInformation' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiGetShippingInformation',
            'getShippingInformationResponse' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiGetShippingInformationResponse',
            'getRouting' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiGetRouting',
            'getRoutingResponse' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiGetRoutingResponse',
            'shippingMultiParcelV3' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingMultiParcelV3',
            'shippingMultiParcelV3Response' => '\\SengentoBV\\ChronopostSdk\\Soap\\ShippingService\\Structs\\ChronoApiShippingMultiParcelV3Response',
        ];
    }
}
